[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Netlify CMS admin access
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Git Gateway for Netlify CMS
[[redirects]]
  from = "/.netlify/git/*"
  to = "/.netlify/functions/git-gateway"
  status = 200

# Identity service for authentication
[[redirects]]
  from = "/.netlify/identity/*"
  to = "/.netlify/functions/identity"
  status = 200

# Headers for security and CORS
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Enable Netlify Identity
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }
