backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Site URL for preview - ensure proper token handling
site_url: https://atek-landing.netlify.app
display_url: https://atek-landing.netlify.app

# Logo for admin interface
logo_url: /ATEK IT LOGO white.svg

# Authentication settings
auth:
  providers:
    - name: email

# Editor settings
editor:
  preview: true

# Publish mode
publish_mode: editorial_workflow

# Local backend for development
local_backend: true

collections:
  - name: "careers-regular"
    label: "Regular Job Roles"
    folder: "src/content/careers"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    filter: { field: "experience", value: "Senior Level", negate: true }
    fields:
      - { label: "Job Role", name: "title", widget: "string", hint: "The job title/position name" }
      - { label: "Job Description", name: "description", widget: "text", hint: "Keep this to 2 lines maximum - a brief summary of the role" }
      - { label: "Job Level", name: "experience", widget: "select", options: ["Entry Level", "Mid Level"], hint: "Experience level required" }
      - { label: "Job Location", name: "location", widget: "string", default: "Frisco, Texas", hint: "Work location" }
      - { label: "Job Type/Department", name: "department", widget: "select", options: ["Software & Development", "Engineering & Infrastructure", "Experience & Design", "Quality & Data"], hint: "Which category this job belongs to" }
      - { label: "Employment Type", name: "type", widget: "select", options: ["Full-time", "Part-time", "Contract", "Internship"], default: "Full-time" }
      - { label: "Requirements", name: "requirements", widget: "list", field: { label: "Requirement", name: "requirement", widget: "string" }, default: ["Bachelor's degree or equivalent experience"], collapsed: false }
      - { label: "Responsibilities", name: "responsibilities", widget: "list", field: { label: "Responsibility", name: "responsibility", widget: "string" }, default: ["Collaborate with team members"], collapsed: false }
      - { label: "Benefits", name: "benefits", widget: "list", field: { label: "Benefit", name: "benefit", widget: "string" }, required: false, collapsed: true }
      - { label: "Skills", name: "skills", widget: "list", field: { label: "Skill", name: "skill", widget: "string" }, required: false, collapsed: true }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Publish Date", name: "date", widget: "datetime", default: "" }

  - name: "careers-senior"
    label: "Senior Level Roles"
    folder: "src/content/careers"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    filter: { field: "experience", value: "Senior Level" }
    fields:
      - { label: "Job Role", name: "title", widget: "string", hint: "The senior position title" }
      - { label: "Department", name: "department", widget: "string", hint: "Department or team name" }
      - { label: "Location", name: "location", widget: "string", default: "Frisco, Texas" }
      - { label: "Experience Level", name: "experience", widget: "select", options: ["Senior Level", "Lead/Principal"], default: "Senior Level" }
      - { label: "Salary Range", name: "salary", widget: "string", hint: "e.g., $120,000 - $150,000/year", required: false }
      - { label: "Job Description", name: "description", widget: "markdown", hint: "Detailed description of the senior role" }
      - { label: "Responsibilities", name: "responsibilities", widget: "list", field: { label: "Responsibility", name: "responsibility", widget: "string" }, hint: "Key responsibilities for this senior role" }
      - { label: "Requirements", name: "requirements", widget: "list", field: { label: "Requirement", name: "requirement", widget: "string" }, hint: "Required qualifications and experience" }
      - { label: "Employment Type", name: "type", widget: "select", options: ["Full-time", "Part-time", "Contract"], default: "Full-time" }
      - { label: "Benefits", name: "benefits", widget: "list", field: { label: "Benefit", name: "benefit", widget: "string" }, required: false, collapsed: true }
      - { label: "Skills", name: "skills", widget: "list", field: { label: "Skill", name: "skill", widget: "string" }, required: false, collapsed: true }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Publish Date", name: "date", widget: "datetime", default: "" }

  - name: "career-settings"
    label: "Career Page Settings"
    files:
      - label: "Career Page Content"
        name: "career-page"
        file: "src/content/career-page.md"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
          - { label: "Why Join Section Title", name: "why_join_title", widget: "string" }
          - { label: "Why Join Description", name: "why_join_description", widget: "text" }
          - label: "Benefits"
            name: "benefits"
            widget: "list"
            fields:
              - { label: "Icon", name: "icon", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - { label: "Application Process Title", name: "application_title", widget: "string" }
          - { label: "Application Instructions", name: "application_instructions", widget: "markdown" }
          - { label: "Contact Email", name: "contact_email", widget: "string" }
          - { label: "Office Location", name: "office_location", widget: "string" }
